server:
  port: 9999
  servlet:
    contextpath: "/activiti-app"
spring:
  liquibase:
    enabled: false
  freemarker:
    check-template-location: false
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    open-in-view: true
    generate-ddl: true
  aop:
    proxy-target-class: false




